version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - db-local
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  backend:
    build:
      context: ./src/lab1/
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      DATABASE_HOST: postgres
    networks:
      - db-local
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/persons"]
      interval: 5s
      timeout: 10s

networks:
  db-local:
    driver: bridge

volumes:
  db-data:
