version: '3.4'

services:
  ds_lab1_api:
    image: ${DOCKER_REGISTRY-}dslab1api
    container_name: ds_lab_api
    build:
      context: .
      dockerfile: DS_Lab1_API/Dockerfile
    networks:
      - api-gateaway
      - database
    ports:
      - "5000:80"

  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - database

volumes:
  db-data:

networks:
  api-gateaway:
    driver: bridge

  database:
    driver: bridge
    internal: true  